# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ocr_server.proto\"\x15\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"+\n\x0fStoreImageParam\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\n\n\x02id\x18\x02 \x01(\t\"\x1c\n\x05\x45mpty\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t2S\n\tOCRServer\x12\x1c\n\tImageSync\x12\x06.Image\x1a\x05.Text\"\x00\x12(\n\nStoreImage\x12\x10.StoreImageParam\x1a\x06.Empty\"\x00\x62\x06proto3')



_IMAGE = DESCRIPTOR.message_types_by_name['Image']
_STOREIMAGEPARAM = DESCRIPTOR.message_types_by_name['StoreImageParam']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_TEXT = DESCRIPTOR.message_types_by_name['Text']
Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'ocr_server_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

StoreImageParam = _reflection.GeneratedProtocolMessageType('StoreImageParam', (_message.Message,), {
  'DESCRIPTOR' : _STOREIMAGEPARAM,
  '__module__' : 'ocr_server_pb2'
  # @@protoc_insertion_point(class_scope:StoreImageParam)
  })
_sym_db.RegisterMessage(StoreImageParam)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'ocr_server_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'ocr_server_pb2'
  # @@protoc_insertion_point(class_scope:Text)
  })
_sym_db.RegisterMessage(Text)

_OCRSERVER = DESCRIPTOR.services_by_name['OCRServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE._serialized_start=20
  _IMAGE._serialized_end=41
  _STOREIMAGEPARAM._serialized_start=43
  _STOREIMAGEPARAM._serialized_end=86
  _EMPTY._serialized_start=88
  _EMPTY._serialized_end=116
  _TEXT._serialized_start=118
  _TEXT._serialized_end=138
  _OCRSERVER._serialized_start=140
  _OCRSERVER._serialized_end=223
# @@protoc_insertion_point(module_scope)
